# Generated by Django 3.2.3 on 2021-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UltraSonic', models.IntegerField()),
                ('ImageNumber', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
